from subprocess import Popen
from subprocess import PIPE
import numpy as np
import shlex
import json

from waflib.Configure import conf

top = '.'
out = '.bld'



def options(ctx):

    ctx.load('compiler_c')

    ctx.load('compiler_fc')



def configure(ctx):
    pass
    ctx.load('compiler_fc')
    # Specify search path for static libraries
   #ctx.env.append_unique('STLIBPATH', ['../.bld/fortran', '../.bld/tests/resources'])


def build(ctx):

    #ctx.add_group()
    #src = ['shared_constants.f90', 'slsqp.f', 'slsqp_interface.f90']
    #src = ['slsqp_interface.f90']

    #ctx(features=['fc', 'fcstlib'], source=src, target='slsqp_library', fcflags=['-fPIC'])


    #ctx.add_group()

    import os
    print(os.getcwd())
    from numpy import f2py
    args = '-I.bld -L.bld -lslsqp_library '
    src = open('replacements_f2py.f90', 'rb').read()
    f2py.compile(src, 'replacements_f2py', args, extension='.f90')

    ctx.add_group()

